### PR TITLE
Extract Plugin UI Layout Configs into Resource Files.

### PR DESCRIPTION
**Pull request by patricker**
This allows custom plugins to provide their own UI layout configuration.

### CODE REVIEW

**Comment by jacques-n** [comment]
Thanks for the great patch! Will ping someone to take a look. 

Thanks again for the contribution

**Comment by patricker** [comment]
@jacques-n Thanks, let me know if you or your team have any suggestions for changes.

**Comment by doronrosenberg** [comment]
Sorry for the delay!  We will merge the patch shortly, thanks for the contribution.

**Comment by jacques-n** [comment]
Thanks for the contribution. We've incorporated it into the latest 4.2.1 release!

**Comment by patricker** [comment]
Thanks @jacques-n, I'll have to check it out, we are using 4.1.8 at the moment.

**Pull request closed without merging**
